### ISSUE TITLE
Formatting error + typo in chapter7 notebook: 2.Fine-tuning ADA

### ISSUE THREAD

**Issue by Aya-S** [Denis2054/Transformers-for-NLP-2nd-Edition#2]
1)There is an empty cell under "Step2" as shown below:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/6892158/168117097-765ceb33-6bb1-48ba-8600-5a8a355b6d39.png">
2) [Weights & Biases](https://wandb.ai/site) is spelled as "Wand" not "WandB"
<img width="569" alt="image" src="https://user-images.githubusercontent.com/6892158/168117477-291ca125-acb7-409e-bffd-f74694ccd72c.png">

**Comment by Denis2054** [comment]
Thank you for taking the time to make a comment.
1. The project imported is "pip install wandb" for Weight and Biases. In the notebook, I will have to change the comment in the text cell from "Wand" to "wandb"
2. Yes, there is an empty cell.

Thanks for describing the issues that will be resolved when I update the GitHub site.
I'll then close the issue.

**Comment by Denis2054** [comment]
The notebook is updated.
Thanks again for your comment.

**Comment by Denis2054** [comment]
The GitHub repository is updated but I have to update the Google and other links.

**Comment by Denis2054** [comment]
I'll do this when I update the whole repository this month.

**Comment by Denis2054** [comment]
The notebook is updated.
